{% set version = "2.3.22" %}

package:
  name: qd
  version: {{ version }}

source:
  fn: qd-{{ version }}.tar.gz
  url: http://crd.lbl.gov/~dhbailey/mpdist/qd-{{ version }}.tar.gz
  sha256: ac99d0af29a30bb32968134bc7840378ef5b9f1e3e7d50c34c206f5810386241

build:
  skip: true  # [win]
  number: 1001

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host: []
  run:

test:
  # make check in build.sh runs tests, these check the installation path
  commands:
    - test -d ${PREFIX}/include/qd
    - test -f ${PREFIX}/lib/libqd.a
    - test -f ${PREFIX}/lib/libqdmod.a
    - test -f ${PREFIX}/lib/libqd_f_main.a
    - test -f ${PREFIX}/lib/libqd${SHLIB_EXT}
    - test -f ${PREFIX}/bin/qd-config
    - qd-config --fclibs

about:
  home: http://crd-legacy.lbl.gov/~dhbailey/mpdist/
  license:  LBNL-BSD
  license_file: COPYING
  summary: A C++/Fortran-90 double-double and quad-double package

extra:
  recipe-maintainers:
    - grlee77
    - isuruf
