{% set version = "2.3.23" %}

package:
  name: qd
  version: {{ version }}

source:
  fn: qd-{{ version }}.tar.gz
  url: https://www.davidhbailey.com/dhbsoftware/qd-{{ version }}.tar.gz
  sha256: 30c1ffe46b95a0e9fa91085949ee5fca85f97ff7b41cd5fe79f79bab730206d3


build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage("qd", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host: []
  run:

test:
  # make check in build.sh runs tests, these check the installation path
  commands:
    - test -d ${PREFIX}/include/qd
    - test -f ${PREFIX}/lib/libqd.a
    - test -f ${PREFIX}/lib/libqdmod.a
    - test -f ${PREFIX}/lib/libqd_f_main.a
    - test -f ${PREFIX}/lib/libqd${SHLIB_EXT}
    - test -f ${PREFIX}/bin/qd-config
    - qd-config --fclibs

about:
  home: http://crd-legacy.lbl.gov/~dhbailey/mpdist/
  license:  LBNL-BSD
  license_file: COPYING
  summary: A C++/Fortran-90 double-double and quad-double package

extra:
  recipe-maintainers:
    - grlee77
    - isuruf
