# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ts9Wq9i9DjjNQOS12gBfhHV5DMoszx5/2AotkW9xNs6pfy+Jr4dDqjECibUDbNC5UOo6lezVEVVMGu9pRS4FdjLnOelQ+//7kYosvz6W56qVLILIpMv6STYR2jcLPa2drMDKULKzoDt/21syrd9ENtpbID5h7MlvlehZKYyQHyGyB5VKrKODkdp4GTSf2jd9dSJeqF8axT+LFB4vsP5GdR0tmtS90ClJQY0BMxq7kw3u67y690CT87gK+mrk8cHzIoibEfaP89kqJ8wF5KuGvKNM42JyaDGbwAQQvglRPs3d3stpUGi3r8Sv0ZxWR/Tfv2w1uL6dWD/SK15ZMOR8O+AwWIhXRlksguYlW5ZYQ5dw137tQYGdZJOyRlqpycvseI6z3TwYSqoIdGkRy/DCxkoIBlmnHD+km+Tr71mg7HG8PGkqZ+N0lFTx79F2IUsx4DQ1nTQ2yCD4fBUrhWB9U8y8cRL8wsV3LtRKvvj54QONIIeTN7wvDeHaAndJ/VDibo/8vxNEJgph/AinpAZ6/R1lR2ElTXH9UQsHCoUmZN/VthFAhAfwKLUYFMuHE+TC3VtHBGcgWquy6RtADr/75j3abqYhsdpAsu0g1apBM7340LrwrOb0+GQx4GZOlDuvsCwo7cJtljnEPDHSZboDr+z6tmtCowk8eanKAhEvxEw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
