appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: ts9Wq9i9DjjNQOS12gBfhHV5DMoszx5/2AotkW9xNs6pfy+Jr4dDqjECibUDbNC5UOo6lezVEVVMGu9pRS4FdjLnOelQ+//7kYosvz6W56qVLILIpMv6STYR2jcLPa2drMDKULKzoDt/21syrd9ENtpbID5h7MlvlehZKYyQHyGyB5VKrKODkdp4GTSf2jd9dSJeqF8axT+LFB4vsP5GdR0tmtS90ClJQY0BMxq7kw3u67y690CT87gK+mrk8cHzIoibEfaP89kqJ8wF5KuGvKNM42JyaDGbwAQQvglRPs3d3stpUGi3r8Sv0ZxWR/Tfv2w1uL6dWD/SK15ZMOR8O+AwWIhXRlksguYlW5ZYQ5dw137tQYGdZJOyRlqpycvseI6z3TwYSqoIdGkRy/DCxkoIBlmnHD+km+Tr71mg7HG8PGkqZ+N0lFTx79F2IUsx4DQ1nTQ2yCD4fBUrhWB9U8y8cRL8wsV3LtRKvvj54QONIIeTN7wvDeHaAndJ/VDibo/8vxNEJgph/AinpAZ6/R1lR2ElTXH9UQsHCoUmZN/VthFAhAfwKLUYFMuHE+TC3VtHBGcgWquy6RtADr/75j3abqYhsdpAsu0g1apBM7340LrwrOb0+GQx4GZOlDuvsCwo7cJtljnEPDHSZboDr+z6tmtCowk8eanKAhEvxEw=}
conda_forge_output_validation: true
